project:
  type: website
  output-dir: docs
  
website:
  title: "Dalton Garcia's ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd  
        text: "About Me"
      - href: portfolio-project1/Portofolio_pt1.qmd  
        text: "Himalayan Exploratory Analysis"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

